import {mdiAlert, mdiCheckCircle, mdiPineTree, mdiTableFurniture, mdiFlagTriangle, mdiCamera, mdiCarMultiple, mdiParking, 
	mdiSailBoat, mdiBridge, mdiNature, mdiInformation, mdiWaves, mdiSawBlade,
	mdiBike, mdiDogSide, mdiFish, mdiShipWheel, mdiImageFilterHdr, mdiBeach, mdiCctv, mdiSofaSingle,
	mdiMapMarker, mdiGasStation, mdiSilverwareForkKnife, 
	mdiFood, mdiBeer, mdiGlassWine, mdiDelete, mdiLadder, mdiHelp, mdiDumpTruck, mdiMower,
	mdiBarley, mdiFireHydrant, mdiPaw, mdiAlertOctagon,
	mdiHumanMale, mdiHumanMaleFemale, mdiHumanFemale, mdiKayaking} from '@mdi/js';

// https://materialdesignicons.com
// https://pictogrammers.com/library/mdi/

export const mdiSVGPaths = {
	alert:		mdiAlert,
	beach:		mdiBeach,
	beer:		mdiBeer,
	bike:		mdiBike,
	boat:		mdiSailBoat,
	bridge:		mdiBridge,
	camera:		mdiCamera,
	cars:		mdiCarMultiple,
	cctv:		mdiCctv,
	check:		mdiCheckCircle,
	construction:	mdiDumpTruck,
	dog:		mdiDogSide,
	ffood:		mdiFood,
	fish:		mdiFish,
	flag:		mdiFlagTriangle,
	food:		mdiSilverwareForkKnife,
	gas:		mdiGasStation,
	hydrant:	mdiFireHydrant,
	info:		mdiInformation,
	kayaking:	mdiKayaking,
	ladder:		mdiLadder,
	man:		mdiHumanMale,
	manx:		mdiHumanMaleFemale,
	woman:		mdiHumanFemale,
	marker:		mdiMapMarker,
	mower:		mdiMower,
	nature:		mdiNature,
	parking:	mdiParking,
	picnic:		mdiTableFurniture,
	question:	mdiHelp,
	rock:		mdiImageFilterHdr,
	saw:		mdiSawBlade,
	sofa:	 	mdiSofaSingle,
	stop:		mdiAlertOctagon,
	trash:		mdiDelete,
	tree:		mdiPineTree,
	waves:		mdiWaves,
	weed:		mdiBarley,
	wheel:		mdiShipWheel,
	wildlife:	mdiPaw,
	wine:		mdiGlassWine,
}

export const mdiSVGIcons = {
	_default: {
		path: mdiSVGPaths.marker,
		stroke: '#FFFFFF',
		strokeWidth: 0.5,
		fill: '#000000',
		anchor: [0.5,0.5],
		magnify: 1
	},
	alert:	{path: mdiSVGPaths.alert,fill:'#FF0000', stroke:'#FFFF00', strokeWidth: 1},
	beach:	{path: mdiSVGPaths.beach,fill:'#EEAB04',stroke:'#000000'},
	beer:	{path: mdiSVGPaths.beer,fill:'#d3c934',stroke:'#FFFFFF',strokeWidth: 1.2},
	bike:	{path: mdiSVGPaths.bike},
	blackw:	{path: mdiSVGPaths.wildlife, fill: '#000000'},
	bluew:	{path: mdiSVGPaths.wildlife, fill: '#20A2C6'},
	boat:	{path: mdiSVGPaths.boat,fill:'#A52A2A'},
	bridge:	{path: mdiSVGPaths.bridge,fill:'#8b4513',stroke:'#000000',strokeWidth:0.5,magnify:5},
	brownw:	{path: mdiSVGPaths.wildlife, fill: '#775541'},
	camera:	{path: mdiSVGPaths.camera,fill:'#040421'},
	cars:	{path: mdiSVGPaths.cars,fill:'#A88C8C',stroke:'#000000'},
	cctv:	{path: mdiSVGPaths.cctv,strokeWidth:1,fill:'#7C8216'},
	check:	{path: mdiSVGPaths.check,fill:'green'},
	construction:	{path: mdiSVGPaths.construction, fill: '#E1A911', stroke: '#000000', strokeWidth: 1.0},
	cyanw:	{path: mdiSVGPaths.wildlife, fill: '#00F7D6'},
	dog:	{path: mdiSVGPaths.dog,fill:'#472210ff',stroke:'#000000',magnify:1.5},
	ffood:	{path: mdiSVGPaths.ffood,fill:'#f2eeb3',stroke:'#000000'},
	fish:	{path: mdiSVGPaths.fish,fill:'#F6E35B',stroke:'#000000',strokeWidth:1},
	flag:	{path: mdiSVGPaths.flag,fill:'#EF6C00',anchor:[0,1.0]},
	food:	{path: mdiSVGPaths.food,fill:'#ffffff',stroke:'#000000'},
	gas:	{path: mdiSVGPaths.gas,fill:'#400559',stroke:'#FFFFFF',strokeWidth:1.0},
	grayw:	{path: mdiSVGPaths.wildlife, fill: '#8E908B'},
	greenflag: {path: mdiSVGPaths.flag,fill:'#008800'},
	greenw:	{path: mdiSVGPaths.wildlife, fill: '#228A13'},
	hydrant:	{path: mdiSVGPaths.hydrant, fill: '#DD2E2E'},
	info:	{path: mdiSVGPaths.info,fill:'#0000AA', strokeWidth:1.0},
	kayak: {path: mdiSVGPaths.kayaking,fill:'orange'},
	ladder:	{path: mdiSVGPaths.ladder,fill:'#3F2812', stroke: '#FFFFFF'},
	limew:	{path: mdiSVGPaths.wildlife, fill: '#3FE114'},
	man:	{path: mdiSVGPaths.man,stroke:'#0000AA',fill:'#FFFFFF'},
	manx:	{path: mdiSVGPaths.manx,stroke:'#0000AA',fill:'#FFFFFF'},
	woman:	{path: mdiSVGPaths.woman,stroke:'#0000AA',fill:'#FFFFFF'},
	marker:	{path: mdiSVGPaths.marker,stroke:'#0000AA',fill:'#FFFFFF'},
	mower:	{path: mdiSVGPaths.mower, fill: '#45050F', stroke: '#FFFFFF'},
	nature:	{path: mdiSVGPaths.nature,fill:'#00AA00',anchor:[0.5,1.0]},
	orangew:	{path: mdiSVGPaths.wildlife, fill: '#FFAA00'},
	parking:	{path: mdiSVGPaths.parking,fill:'#0000AA',magnify:2},
	picnic:	{path: mdiSVGPaths.picnic,fill:'#5C2F00'},
	pinkw:	{path: mdiSVGPaths.wildlife, fill: '#FF0093'},
	purplew:	{path: mdiSVGPaths.wildlife, fill: '#960A96'},
	question:	{path: mdiSVGPaths.question,fill:'#6D0E0E', stroke: '#B0891E'},
	redw:	{path: mdiSVGPaths.wildlife, fill: '#FF0000'},
	rock:	{path: mdiSVGPaths.rock,fill:'#70BB0A',stroke:'#000000'}, 
	saw:	{path: mdiSVGPaths.saw,fill:'#333333',stroke:'#000000'},
	sofa:	{path: mdiSVGPaths.sofa,fill:'#260D4E'},
	stop:	{path: mdiSVGPaths.stop,fill:'#FF0000', stroke:'#FFFF00', strokeWidth: 1.2},
	tanw:	{path: mdiSVGPaths.wildlife, fill: '#B6783F'},
	tealw:	{path: mdiSVGPaths.wildlife, fill: '#42806D'},
	trash:	{path: mdiSVGPaths.trash,fill:'#000000'},
	tree:	{path: mdiSVGPaths.tree,fill:'green'},
	waves:	{path: mdiSVGPaths.waves,fill:'#000066'},
	weed:	{path: mdiSVGPaths.weed, fill: '#A3A113', stroke: '#FFFFFF'},
	wheel:	{path: mdiSVGPaths.wheel,fill:'#5C2F00',magnify:5},
	whitew:	{path: mdiSVGPaths.wildlife, fill: '#FFFFFF'},
	wine:	{path: mdiSVGPaths.wheel,fill:'#9e0c35'},
	yelloww:	{path: mdiSVGPaths.wildlife, fill: '#DFF007'},
}

export function getSVGIcon(icoName: string): string {
	var icon = Object.assign({},mdiSVGIcons._default,mdiSVGIcons[icoName]);

	var path = '<path';
	if (icon.strokeWidth > 0) {
		path += ` stroke="${icon.stroke}" stroke-width="${icon.strokeWidth}"`;
	}
	path += ` fill="${icon.fill}" d="${icon.path}"/>`;

	let width  = 48 * icon.magnify;
	let height = 48 * icon.magnify;
	return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 24 24">${path}</svg>`;
}
