fvrIcons: [backburger,city,cog,directions,goback,home,information,layers,link,menu,github,facebook,instagram,twitter,donate,ishare,natureman,together,voice,walk,refresh]
pageIncludes: [pages]
mapIncludes: [biketrails,trails,markers]
